# Generated by Django 5.0.2 on 2024-02-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='total_delivery_price',
        ),
    ]
