# Generated by Django 5.0.2 on 2024-02-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_alter_pricing_item_id_alter_pricing_organization_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_price_per_pack',
            field=models.CharField(default=10, max_length=200),
            preserve_default=False,
        ),
    ]
